### ISSUE TITLE
Make clear that CLOPS runs take longer than 10min

### ISSUE THREAD

**Issue by nonhermitian** [qiskit-community/qiskit-device-benchmarking#36]
The CLOPS readme currently says it will take around 10min.  However, actual execution of the script is ~56min.  Perhaps the readme should be updated to say runtime is ~1hr

**Comment by dcmckayibm** [comment]
@andrewwack ?

**Comment by dcmckayibm** [comment]
I also found it took fairly long to run so it was a bit confusing to me as well

**Comment by andrewwack** [comment]
Hmm, let me look.  It shouldn't be that long, but may be longer than 10 minutes.

**Comment by dcmckayibm** [comment]
Thanks, I'll close.
